name: search_app_bar
description: An animated SearchAppBar library that makes it easy to control the search for any type of data in a list of elements.
version: 1.0.2+2
author: Rodolfo Gusson <rodolfoggp@gmail.com>
homepage: https://github.com/rodolfoggp/search_app_bar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_pattern: ^3.0.0
  rxdart: ^0.27.1
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: